#define CMD_STARRED 1
#define CMD_SEARCH 2
#define CMD_SHUFFLE 4
#define CMD_REPEAT 5
#define CMD_ALWAYS_ON_TOP 6
#define CMD_DOUBLE_SIZE 7
#define CMD_EASYMOVE 8
#define CMD_PREFS 9
#define CMD_TIME_ELAPSED 10
#define CMD_TIME_REMAINS 11
#define CMD_LOGIN 12

#define CMD_BITRATE_LO 13
#define CMD_BITRATE_MED 14
#define CMD_BITRATE_HI 15

#define CMD_SHOUTCAST 16
#define CMD_VISUALIZER_STARTSTOP 17
#define CMD_VISUALIZER_CONFIG 18
#define CMD_ABOUT 19
#define CMD_EXIT 20

#define CMD_LEGAL0 21
#define CMD_LEGAL1 22
#define CMD_LEGAL2 23

#define CMD_PLAY 24
#define CMD_PAUSE 25
#define CMD_STOP 26
#define CMD_PREV 27
#define CMD_NEXT 28
#define CMD_VOLUME_UP 29
#define CMD_VOLUME_DOWN 30
#define CMD_FORWARD 31
#define CMD_REWIND 32
#define CMD_OPENFILE 33
#define CMD_PLAY_CLIPBOARD 34
#define CMD_COMPACT 35
#define CMD_TIME_TOGGLE 36
#define CMD_EQ_TOGGLE 37
#define CMD_PLAYLIST_TOGGLE 38
#define CMD_PLAYPAUSE 39
#define CMD_MINIMIZE 40
#define CMD_OPTIONS 41
#define CMD_VISUALIZER_MENU 42
#define CMD_BRINGTOTOP 43
#define CMD_GLOBAL_HOTKEYS 44

#define CMD_ARTIST_RADIO 45
#define CMD_ALBUM_RADIO 46
#define CMD_TRACK_RADIO 47
#define CMD_PLAYLIST_RADIO 48
#define CMD_GOTO_ALBUM 49
#define CMD_PLAYLIST_PLAY 50

#define CMD_COPY_TRACK 51
#define CMD_COPY_ALBUM 52
#define CMD_COPY_ARTIST 53
#define CMD_COPY_PLAYLIST 54

#define CMD_OPEN_IN_BROWSER 55
#define CMD_PLAYLIST_ADD_TO_LAST 56

#define CMD_TOGGLE_ALBUMART 57

#define CMD_RADIO 0x1000
#define CMD_PLAYLIST 0x2000
#define CMD_VISUALIZER 0x3000
#define CMD_SKIN 0x4000
#define CMD_PLAYLIST_ADD_TO 0x5000
#define CMD_OUTPUT_DEVICE 0x6000
#define CMD_TOPLIST 0x7000
#define CMD_REMOTE_DEVICE 0x8000
